spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/food_for_you?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234a

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      show_sql: true
    properties:
      hibernate:
        auto_quote_keyword: true
        format_sql: true
      use_sql_comments: true



